---
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5415:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://sushruta:sushruta_dev_password@db:5432/sushruta?sslmode=disable
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=sushruta
      - DATABASE_PASSWORD=sushruta_dev_password
      - DATABASE_NAME=sushruta
      - PORT=3000
      - LOG_LEVEL=info
      - CORS_ORIGINS=*
    volumes:
      - ./backend/src:/app/src
      - ./backend/database:/app/database
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5416:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sushruta
      - POSTGRES_USER=sushruta
      - POSTGRES_PASSWORD=sushruta_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  backend_node_modules:
  frontend_node_modules:
  postgres_data:

networks:
  default:
    name: sushruta_network